### ISSUE TITLE
Gå tillbaka-länken fungerar inte

### ISSUE THREAD

**Issue by js223kz** [AndreasAnemyrLNU/1DV450-Webbramverk#2]
När man går till sidan Apikeys eller Keytable och inte är inloggad kan man inte använda tillbaka-länken. Där har också smugit sig in lite svenska.

**Comment by AndreasAnemyrLNU** [comment]
Länk var publicerad men var borttagen i min lokala utvecklingsmiljö.
Jag ska se över vad som kan vara en bättre lösning :+1:
