### ISSUE TITLE
Mina högst personliga reflektioner

### ISSUE THREAD

**Issue by js223kz** [AndreasAnemyrLNU/1DV450-Webbramverk#4]
Hej Andreas,
här kommer några synpunkter som inte är buggar och därför ville jag inte skriva dem som issues, men vill ändå dela med mig av dem.
1. När jag är på registreringssidan visas ett meddelande om att jag inte är inloggad. Känns lite som att konstatera det uppenbara.
2. Det skulle kännas proffsigare om Logga in döljs om jag är inloggad och logga ut döljs om jag inte är inloggad.
3. Validering av modellerna. Det finns ju validering på klienten, men Mats ord ringer i mina öron. Man ska både ha hänglsen och bälte på. Kanske emailvalidering och minimumlängd på lösenordet. 
4. Det finns ett stavfel på sidan skapa ny nyckel. Det står kew istället för key.
5. Jag skulle valt att tilldela apikey sitt värde i modellen och inte i controllern.
6. När jag loggat in och kan se alla mina nycklar upplever jag som användare att det skulle vara praktiskt om formuläret för att lägga till nycklar fanns på samma sida. Ingen stor grej, men det är lite störigt att behöva gå upp i dropdownmenyn för det.
7. Förstår att du inte lagt någon energi på design så det är väl att konstatera det uppenbara att den är tråkig.
8. Du får lite onödiga "döda" url:er i och med rescoures: apikeys. Det är mer specificerat vid user, login, registera.

Som sagt detta är mina personliga åsikter och behöver inte alls vara det som är rätt.

**Comment by AndreasAnemyrLNU** [comment]
Hej Johanna!

Tack så mycket för din feedback.
Tar del och förändrar en del :)

//Andréas

Den 1 mars 2016 09:33 skrev Johanna Szepanski notifications@github.com:

**Comment by AndreasAnemyrLNU** [comment]
#4 fixad 9/3 -16
